using HueApi.Models;
using HueApi.Models.Sensors;
using System.Text.Json.Serialization;

namespace HueApi
{
  [JsonSerializable(typeof(HueResponse<HueResource>))]
  [JsonSerializable(typeof(HueResponse<Light>))]
  [JsonSerializable(typeof(HueResponse<Scene>))]
  [JsonSerializable(typeof(HueResponse<Room>))]
  [JsonSerializable(typeof(HueResponse<Zone>))]
  [JsonSerializable(typeof(HueResponse<BridgeHome>))]
  [JsonSerializable(typeof(HueResponse<GroupedLight>))]
  [JsonSerializable(typeof(HueResponse<Device>))]
  [JsonSerializable(typeof(HueResponse<Bridge>))]
  [JsonSerializable(typeof(HueResponse<DeviceSoftwareUpdate>))]
  [JsonSerializable(typeof(HueResponse<DevicePower>))]
  [JsonSerializable(typeof(HueResponse<ZigbeeConnectivity>))]
  [JsonSerializable(typeof(HueResponse<ZgpConnectivity>))]
  [JsonSerializable(typeof(HueResponse<ZigbeeDeviceDiscovery>))]
  [JsonSerializable(typeof(HueResponse<MotionResource>))]
  [JsonSerializable(typeof(HueResponse<ServiceGroupResource>))]
  [JsonSerializable(typeof(HueResponse<GroupedMotionResource>))]
  [JsonSerializable(typeof(HueResponse<GroupedLightLevelResource>))]
  [JsonSerializable(typeof(HueResponse<CameraMotionResource>))]
  [JsonSerializable(typeof(HueResponse<TemperatureResource>))]
  [JsonSerializable(typeof(HueResponse<LightLevelResource>))]
  [JsonSerializable(typeof(HueResponse<ButtonResource>))]
  [JsonSerializable(typeof(HueResponse<BellButtonResource>))]
  [JsonSerializable(typeof(HueResponse<RelativeRotaryResource>))]
  [JsonSerializable(typeof(HueResponse<BehaviorScript>))]
  [JsonSerializable(typeof(HueResponse<BehaviorInstance>))]
  [JsonSerializable(typeof(HueResponse<GeofenceClient>))]
  [JsonSerializable(typeof(HueResponse<Geolocation>))]
  [JsonSerializable(typeof(HueResponse<EntertainmentConfiguration>))]
  [JsonSerializable(typeof(HueResponse<Entertainment>))]
  [JsonSerializable(typeof(HueResponse<Homekit>))]
  [JsonSerializable(typeof(HueResponse<MatterItem>))]
  [JsonSerializable(typeof(HueResponse<MatterFabric>))]
  [JsonSerializable(typeof(HueResponse<SmartScene>))]
  [JsonSerializable(typeof(HueResponse<ContactSensor>))]
  [JsonSerializable(typeof(HueResponse<TamperSensor>))]
  [JsonSerializable(typeof(HueResponse<MotionAreaConfigResource>))]
  [JsonSerializable(typeof(HueResponse<MotionAreaCandidateResource>))]
  [JsonSerializable(typeof(HueResponse<ConvenienceAreaMotionResource>))]
  [JsonSerializable(typeof(HueResponse<SecurityAreaMotionResource>))]
  [JsonSerializable(typeof(HueResponse<SpeakerResource>))]
  [JsonSerializable(typeof(HueResponse<ClipResource>))]
  [JsonSerializable(typeof(HueResponse<WifiConnectivityResource>))]
  [JsonSerializable(typeof(HueResponse<ResourceIdentifier>))]
  public partial class HueJsonSerializerContext : JsonSerializerContext { }
}
